name: Build binaries for macOS and Linux, publish Node.js packages, create release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos-x64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Package
        run: |
          npm i
          npm run build
          npm run package:macos:x64

      - name: Create tarball
        run: |
          mv bin/macos-x64/unleash unleash
          tar -cvzf unleash-macos-x64.tar.gz unleash

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v2
        with:
          name: bin-macos-x64
          path: unleash-macos-x64.tar.gz

  build-macos-arm64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Package
        run: |
          npm i
          npm run build
          npm run package:macos:arm64

      - name: Create tarball
        run: |
          mv bin/macos-arm64/unleash unleash
          tar -cvzf unleash-macos-arm64.tar.gz unleash

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v2
        with:
          name: bin-macos-arm64
          path: unleash-macos-arm64.tar.gz

  build-linux-x64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Package
        run: |
          npm i
          npm run build
          npm run package:linux:x64

      - name: Create tarball
        run: |
          mv bin/linux-x64/unleash unleash
          tar -cvzf unleash-linux-x64.tar.gz unleash

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v2
        with:
          name: bin-linux-x64
          path: unleash-linux-x64.tar.gz

  build-linux-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Package
        run: |
          npm i
          npm run build
          npm run package:linux:arm64

      - name: Create tarball
        run: |
          mv bin/linux-arm64/unleash unleash
          tar -cvzf unleash-linux-arm64.tar.gz unleash

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v2
        with:
          name: bin-linux-arm64
          path: unleash-linux-arm64.tar.gz

  publish-node-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Build and publish to npm registry
        continue-on-error: true
        run: |
          npm i
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish to GitHub registry
        continue-on-error: true
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    needs: [build-macos-x64, build-macos-arm64, build-linux-x64, build-linux-arm64, publish-node-packages]

    runs-on: ubuntu-latest

    steps:
      - name: Download macos-x64 tarball
        uses: actions/download-artifact@v2
        with:
          name: bin-macos-x64

      - name: Download macos-x64 tarball
        uses: actions/download-artifact@v2
        with:
          name: bin-macos-arm64

      - name: Download linux tarball
        uses: actions/download-artifact@v2
        with:
          name: bin-linux-x64
      
      - name: Download linux tarball
        uses: actions/download-artifact@v2
        with:
          name: bin-linux-arm64

      - name: Compute checksums
        run: |
          sha256sum unleash-macos-x64.tar.gz >> checksums.md
          sha256sum unleash-macos-arm64.tar.gz >> checksums.md
          sha256sum unleash-linux-x64.tar.gz >> checksums.md
          sha256sum unleash-linux-arm64.tar.gz >> checksums.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          body_path: checksums.md
          files: |
            unleash-macos-x64.tar.gz
            unleash-macos-arm64.tar.gz
            unleash-linux-x64.tar.gz
            unleash-linux-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}